const sampleProducts = [
    { id: '0x020000', groupId: 1, image: 'https://via.placeholder.com/200', title: 'HyperTech m2 external case SSD', inStock: true, price: 19.99, brand: 'HyperTech', type: 'm2 external case', color: 'Black' },
    { id: '0x020001', groupId: 2, image: 'https://via.placeholder.com/200', title: 'CyberTech sata external case SSD', inStock: false, price: 29.99, brand: 'CyberTech', type: 'sata external case', color: 'Silver' },
    { id: '0x020002', groupId: -1, image: 'https://via.placeholder.com/200', title: 'NanoTech sata adapter SSD', inStock: true, price: 9.99, brand: 'NanoTech', type: 'sata adapter' },
    { id: '0x020003', groupId: -1, image: 'https://via.placeholder.com/200', title: 'QuantumTech m2 adapter SSD', inStock: false, price: 49.99, brand: 'QuantumTech', type: 'm2 adapter' },
    { id: '0x020004', groupId: -1, image: 'https://via.placeholder.com/200', title: 'VertexTech pci adapter SSD', inStock: true, price: 39.99, brand: 'VertexTech', type: 'pci adapter' },
    { id: '0x020005', groupId: -1, image: 'https://via.placeholder.com/200', title: 'MegaTech docker SSD', inStock: true, price: 21.99, brand: 'MegaTech', type: 'docker' },
    { id: '0x020006', groupId: -1, image: 'https://via.placeholder.com/200', title: 'TitanTech cooling SSD', inStock: false, price: 25.99, brand: 'TitanTech', type: 'cooling' },
    { id: '0x020007', groupId: -1, image: 'https://via.placeholder.com/200', title: 'AeroTech caddy adapter SSD', inStock: true, price: 14.99, brand: 'AeroTech', type: 'caddy adapter' },
    { id: '0x020008', groupId: -1, image: 'https://via.placeholder.com/200', title: 'FusionTech sata cables SSD', inStock: false, price: 34.99, brand: 'FusionTech', type: 'sata cables' },
    { id: '0x020009', groupId: 3, image: 'https://via.placeholder.com/200', title: 'NexusTech m2 external case SSD', inStock: true, price: 45.99, brand: 'NexusTech', type: 'm2 external case', color: 'Red' },
    { id: '0x02000A', groupId: 4, image: 'https://via.placeholder.com/200', title: 'HyperTech sata external case SSD', inStock: true, price: 19.99, brand: 'HyperTech', type: 'sata external case', color: 'Blue' },
    { id: '0x02000B', groupId: -1, image: 'https://via.placeholder.com/200', title: 'CyberTech sata adapter SSD', inStock: false, price: 29.99, brand: 'CyberTech', type: 'sata adapter' },
    { id: '0x02000C', groupId: -1, image: 'https://via.placeholder.com/200', title: 'NanoTech m2 adapter SSD', inStock: true, price: 9.99, brand: 'NanoTech', type: 'm2 adapter' },
    { id: '0x02000D', groupId: -1, image: 'https://via.placeholder.com/200', title: 'QuantumTech pci adapter SSD', inStock: false, price: 49.99, brand: 'QuantumTech', type: 'pci adapter' },
    { id: '0x02000E', groupId: -1, image: 'https://via.placeholder.com/200', title: 'VertexTech docker SSD', inStock: true, price: 39.99, brand: 'VertexTech', type: 'docker' },
    { id: '0x02000F', groupId: -1, image: 'https://via.placeholder.com/200', title: 'MegaTech cooling SSD', inStock: true, price: 21.99, brand: 'MegaTech', type: 'cooling' },
    { id: '0x020010', groupId: -1, image: 'https://via.placeholder.com/200', title: 'TitanTech caddy adapter SSD', inStock: false, price: 25.99, brand: 'TitanTech', type: 'caddy adapter' },
    { id: '0x020011', groupId: -1, image: 'https://via.placeholder.com/200', title: 'AeroTech sata cables SSD', inStock: true, price: 14.99, brand: 'AeroTech', type: 'sata cables' },
    { id: '0x020012', groupId: 5, image: 'https://via.placeholder.com/200', title: 'FusionTech m2 external case SSD', inStock: false, price: 34.99, brand: 'FusionTech', type: 'm2 external case', color: 'Green' },
    { id: '0x020013', groupId: 6, image: 'https://via.placeholder.com/200', title: 'NexusTech sata external case SSD', inStock: true, price: 45.99, brand: 'NexusTech', type: 'sata external case', color: 'Yellow' },
    { id: '0x020014', groupId: -1, image: 'https://via.placeholder.com/200', title: 'HyperTech sata adapter SSD', inStock: true, price: 19.99, brand: 'HyperTech', type: 'sata adapter' },
    { id: '0x020015', groupId: -1, image: 'https://via.placeholder.com/200', title: 'CyberTech m2 adapter SSD', inStock: false, price: 29.99, brand: 'CyberTech', type: 'm2 adapter' },
    { id: '0x020016', groupId: -1, image: 'https://via.placeholder.com/200', title: 'NanoTech pci adapter SSD', inStock: true, price: 9.99, brand: 'NanoTech', type: 'pci adapter' },
    { id: '0x020017', groupId: -1, image: 'https://via.placeholder.com/200', title: 'QuantumTech docker SSD', inStock: false, price: 49.99, brand: 'QuantumTech', type: 'docker' },
    { id: '0x020018', groupId: -1, image: 'https://via.placeholder.com/200', title: 'VertexTech cooling SSD', inStock: true, price: 39.99, brand: 'VertexTech', type: 'cooling' },
    { id: '0x020019', groupId: -1, image: 'https://via.placeholder.com/200', title: 'MegaTech caddy adapter SSD', inStock: true, price: 21.99, brand: 'MegaTech', type: 'caddy adapter' },
    { id: '0x02001A', groupId: -1, image: 'https://via.placeholder.com/200', title: 'TitanTech sata cables SSD', inStock: false, price: 25.99, brand: 'TitanTech', type: 'sata cables' },
    { id: '0x02001B', groupId: 7, image: 'https://via.placeholder.com/200', title: 'AeroTech m2 external case SSD', inStock: true, price: 14.99, brand: 'AeroTech', type: 'm2 external case', color: 'White' },
    { id: '0x02001C', groupId: -1, image: 'https://via.placeholder.com/200', title: 'FusionTech sata external case SSD', inStock: false, price: 34.99, brand: 'FusionTech', type: 'sata external case', color: 'Purple' },
    { id: '0x02001D', groupId: -1, image: 'https://via.placeholder.com/200', title: 'NexusTech sata adapter SSD', inStock: true, price: 45.99, brand: 'NexusTech', type: 'sata adapter' }
];

export default sampleProducts