const sampleProducts = [
    { id: '0x010001', groupId: 0, image: 'https://via.placeholder.com/200', title: 'Adata 120GB USB Type A SSD', inStock: true, price: 19.99, brand: 'Adata', type: 'USB Type A', size: '120GB', color: 'Black' },
    { id: '0x010002', groupId: 1, image: 'https://via.placeholder.com/200', title: 'Samsung 240GB USB Type C SSD', inStock: false, price: 29.99, brand: 'Samsung', type: 'USB Type C', size: '240GB', color: 'Silver' },
    { id: '0x010003', groupId: 2, image: 'https://via.placeholder.com/200', title: 'Kingston 500GB USB Type A SSD', inStock: true, price: 9.99, brand: 'Kingston', type: 'USB Type A', size: '500GB', color: 'Red' },
    { id: '0x010004', groupId: 3, image: 'https://via.placeholder.com/200', title: 'SanDisk 1TB USB Type C SSD', inStock: false, price: 49.99, brand: 'SanDisk', type: 'USB Type C', size: '1TB', color: 'Blue' },
    { id: '0x010005', groupId: 4, image: 'https://via.placeholder.com/200', title: 'WD 2TB USB Type A SSD', inStock: true, price: 39.99, brand: 'WD', type: 'USB Type A', size: '2TB', color: 'Green' },
    { id: '0x010006', groupId: 5, image: 'https://via.placeholder.com/200', title: 'Seagate 120GB USB Type C SSD', inStock: true, price: 21.99, brand: 'Seagate', type: 'USB Type C', size: '120GB', color: 'Black' },
    { id: '0x010007', groupId: 0, image: 'https://via.placeholder.com/200', title: 'Adata 240GB USB Type A SSD', inStock: false, price: 25.99, brand: 'Adata', type: 'USB Type A', size: '240GB', color: 'Silver' },
    { id: '0x010008', groupId: 1, image: 'https://via.placeholder.com/200', title: 'Samsung 500GB USB Type C SSD', inStock: true, price: 14.99, brand: 'Samsung', type: 'USB Type C', size: '500GB', color: 'Red' },
    { id: '0x010009', groupId: 2, image: 'https://via.placeholder.com/200', title: 'Kingston 1TB USB Type A SSD', inStock: false, price: 34.99, brand: 'Kingston', type: 'USB Type A', size: '1TB', color: 'Blue' },
    { id: '0x01000A', groupId: 3, image: 'https://via.placeholder.com/200', title: 'SanDisk 2TB USB Type C SSD', inStock: true, price: 45.99, brand: 'SanDisk', type: 'USB Type C', size: '2TB', color: 'Green' },
    { id: '0x01000B', groupId: 4, image: 'https://via.placeholder.com/200', title: 'WD 120GB USB Type A SSD', inStock: true, price: 19.99, brand: 'WD', type: 'USB Type A', size: '120GB', color: 'Black' },
    { id: '0x01000C', groupId: 5, image: 'https://via.placeholder.com/200', title: 'Seagate 240GB USB Type C SSD', inStock: false, price: 29.99, brand: 'Seagate', type: 'USB Type C', size: '240GB', color: 'Silver' },
    { id: '0x01000D', groupId: 0, image: 'https://via.placeholder.com/200', title: 'Adata 500GB USB Type A SSD', inStock: true, price: 9.99, brand: 'Adata', type: 'USB Type A', size: '500GB', color: 'Red' },
    { id: '0x01000E', groupId: 1, image: 'https://via.placeholder.com/200', title: 'Samsung 1TB USB Type C SSD', inStock: false, price: 49.99, brand: 'Samsung', type: 'USB Type C', size: '1TB', color: 'Blue' },
    { id: '0x01000F', groupId: 2, image: 'https://via.placeholder.com/200', title: 'Kingston 2TB USB Type A SSD', inStock: true, price: 39.99, brand: 'Kingston', type: 'USB Type A', size: '2TB', color: 'Green' },
    { id: '0x010010', groupId: 3, image: 'https://via.placeholder.com/200', title: 'SanDisk 120GB USB Type C SSD', inStock: true, price: 21.99, brand: 'SanDisk', type: 'USB Type C', size: '120GB', color: 'Black' },
    { id: '0x010011', groupId: 4, image: 'https://via.placeholder.com/200', title: 'WD 240GB USB Type A SSD', inStock: false, price: 25.99, brand: 'WD', type: 'USB Type A', size: '240GB', color: 'Silver' },
    { id: '0x010012', groupId: 5, image: 'https://via.placeholder.com/200', title: 'Seagate 500GB USB Type C SSD', inStock: true, price: 14.99, brand: 'Seagate', type: 'USB Type C', size: '500GB', color: 'Red' },
    { id: '0x010013', groupId: 0, image: 'https://via.placeholder.com/200', title: 'Adata 1TB USB Type A SSD', inStock: false, price: 34.99, brand: 'Adata', type: 'USB Type A', size: '1TB', color: 'Blue' },
    { id: '0x010014', groupId: 1, image: 'https://via.placeholder.com/200', title: 'Samsung 2TB USB Type C SSD', inStock: true, price: 45.99, brand: 'Samsung', type: 'USB Type C', size: '2TB', color: 'Green' },
    { id: '0x010015', groupId: 2, image: 'https://via.placeholder.com/200', title: 'Kingston 120GB USB Type A SSD', inStock: true, price: 19.99, brand: 'Kingston', type: 'USB Type A', size: '120GB', color: 'Black' },
    { id: '0x010016', groupId: 3, image: 'https://via.placeholder.com/200', title: 'SanDisk 240GB USB Type C SSD', inStock: false, price: 29.99, brand: 'SanDisk', type: 'USB Type C', size: '240GB', color: 'Silver' },
    { id: '0x010017', groupId: 4, image: 'https://via.placeholder.com/200', title: 'WD 500GB USB Type A SSD', inStock: true, price: 9.99, brand: 'WD', type: 'USB Type A', size: '500GB', color: 'Red' },
    { id: '0x010018', groupId: 5, image: 'https://via.placeholder.com/200', title: 'Seagate 1TB USB Type C SSD', inStock: false, price: 49.99, brand: 'Seagate', type: 'USB Type C', size: '1TB', color: 'Blue' },
    { id: '0x010019', groupId: 0, image: 'https://via.placeholder.com/200', title: 'Adata 2TB USB Type A SSD', inStock: true, price: 39.99, brand: 'Adata', type: 'USB Type A', size: '2TB', color: 'Green' },
    { id: '0x01001A', groupId: 1, image: 'https://via.placeholder.com/200', title: 'Samsung 120GB USB Type C SSD', inStock: true, price: 21.99, brand: 'Samsung', type: 'USB Type C', size: '120GB', color: 'Black' },
    { id: '0x01001B', groupId: 2, image: 'https://via.placeholder.com/200', title: 'Kingston 240GB USB Type A SSD', inStock: false, price: 25.99, brand: 'Kingston', type: 'USB Type A', size: '240GB', color: 'Silver' },
    { id: '0x01001C', groupId: 3, image: 'https://via.placeholder.com/200', title: 'SanDisk 500GB USB Type C SSD', inStock: true, price: 14.99, brand: 'SanDisk', type: 'USB Type C', size: '500GB', color: 'Red' },
    { id: '0x01001D', groupId: 4, image: 'https://via.placeholder.com/200', title: 'WD 1TB USB Type A SSD', inStock: false, price: 34.99, brand: 'WD', type: 'USB Type A', size: '1TB', color: 'Blue' },
    { id: '0x01001E', groupId: 5, image: 'https://via.placeholder.com/200', title: 'Seagate 2TB USB Type C SSD', inStock: true, price: 45.99, brand: 'Seagate', type: 'USB Type C', size: '2TB', color: 'Green' }
];

export default sampleProducts